name: AdventOfCode
description: Package for solving problems for Advent of Code
dependencies:
  ansicolor: ^2.0.2
  collection: ^1.18.0
  dart_numerics: ^0.0.6
  trotter: ^2.2.0
  http: ^1.1.2
  advance_math: ^5.4.3

environment:
  sdk: '^3.2.0'